version: '3.7'

networks:
  internal:
    external: false # Create the volume if it doesn't exist
    name: infrastructure_network

volumes:
  redis_data:
    external: false # Create the volume if it doesn't exist
    name: redis_data

services:
  redis:
    hostname: redis
    container_name: redis
    image: redis:6.0-rc1
    expose:
      - 6379
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - internal
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - internal
